# ============================================================
# Script 02: LinDA Alternative Differential Abundance Analysis
# Candrea et al. - Gut Microbiota Comparative Analysis
# Biomedicines 2025
# ============================================================
# Description:
# Taxon-level differential abundance analysis using LinDA
# (Linear Models for Differential Abundance Analysis).
# Analyses performed at phylum and genus level.
# Each study group is used as reference in turn to obtain
# all pairwise comparisons.
# Multiple testing correction: Benjamini-Hochberg FDR.
#
# Reference: Zhou H, et al. Genome Biol. 2022;23(1):95.
#            DOI: 10.1186/s13059-022-02655-5
#
# Input files (generated by 01_data_preparation.R):
#   - linda_otu_phylum.csv
#   - linda_otu_genus.csv
#   - linda_meta_phylum.csv
#
# Output:
#   - linda_results_ALL_LEVELS.csv
#   - linda_results_reference_HC.csv
#   - linda_results_reference_AG.csv
#   - linda_results_reference_AI.csv
#   - linda_results_reference_IBS.csv
#
# Software: R version 4.5.3, MicrobiomeStat v1.18
# ============================================================

if (!requireNamespace("MicrobiomeStat", quietly = TRUE)) {
  install.packages("MicrobiomeStat")
}
library(MicrobiomeStat)

# ============================================================
# LOAD DATA
# ============================================================

otu_phylum <- read.csv("linda_otu_phylum.csv", row.names = 1, check.names = FALSE)
otu_genus  <- read.csv("linda_otu_genus.csv",  row.names = 1, check.names = FALSE)
meta       <- read.csv("linda_meta_phylum.csv", row.names = 1)

# Align samples
common_samples <- intersect(colnames(otu_phylum), rownames(meta))
otu_phylum <- otu_phylum[, common_samples]
otu_genus  <- otu_genus[,  common_samples]
meta       <- meta[common_samples, , drop = FALSE]

cat("Samples:", ncol(otu_phylum), "\n")
cat("Groups:", table(meta$Group), "\n")

# ============================================================
# FUNCTION: run LinDA for one level and one reference group
# ============================================================

run_linda <- function(otu_data, meta_data, ref_group, level_name) {

  meta_ref       <- meta_data
  meta_ref$Group <- relevel(factor(meta_ref$Group), ref = ref_group)

  linda_obj <- linda(
    feature.dat      = as.matrix(otu_data),
    meta.dat         = meta_ref,
    formula          = "~Group",
    feature.dat.type = "proportion",
    prev.filter      = 0.1,        # minimum prevalence filter 10%
    p.adj.method     = "BH",       # Benjamini-Hochberg FDR
    alpha            = 0.05,
    verbose          = FALSE
  )

  results_list <- lapply(names(linda_obj$output), function(comp) {
    res <- linda_obj$output[[comp]]
    data.frame(
      Level          = level_name,
      Taxon          = rownames(res),
      Comparison     = paste0(gsub("Group", "", comp), "_vs_", ref_group),
      log2FoldChange = round(res$log2FoldChange, 4),
      lfcSE          = round(res$lfcSE, 4),
      pvalue         = round(res$pvalue, 4),
      padj           = round(res$padj, 4)
    )
  })

  do.call(rbind, results_list)
}

# ============================================================
# RUN LINDA ITERATIVELY FOR ALL REFERENCE GROUPS
# All pairwise comparisons as stated in Methods
# ============================================================

reference_groups <- c("HC", "AG", "AI", "IBS")
all_results      <- data.frame()

for (ref in reference_groups) {

  cat("\n--- Running LinDA: reference =", ref, "---\n")

  res_phylum <- run_linda(otu_phylum, meta, ref, "Phylum")
  res_genus  <- run_linda(otu_genus,  meta, ref, "Genus")

  combined    <- rbind(res_phylum, res_genus)
  all_results <- rbind(all_results, combined)

  # Save per reference
  outfile <- paste0("linda_results_reference_", ref, ".csv")
  write.csv(combined, outfile, row.names = FALSE)

  # Print significant FDR < 0.05
  sig <- combined[combined$padj < 0.05, ]
  if (nrow(sig) > 0) {
    cat("Significant FDR < 0.05 (reference =", ref, "):\n")
    print(sig)
  } else {
    cat("No significant taxa (FDR < 0.05) with reference =", ref, "\n")
  }
}

# ============================================================
# SAVE COMBINED RESULTS ALL REFERENCES
# ============================================================

write.csv(all_results, "linda_results_ALL_LEVELS.csv", row.names = FALSE)

cat("\n\nSummary - FDR < 0.05 across all comparisons:\n")
print(all_results[all_results$padj < 0.05, ])

cat("\nAll results saved to: linda_results_ALL_LEVELS.csv\n")
cat("Analysis complete.\n")
